"""
SQLAlchemy 2.0 models for the trading system.
Supports dual accounts, hedge strategy, and full audit trail.
"""
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Optional, Dict, Any

from sqlalchemy import (
    String, Text, Integer, Numeric, DateTime, ForeignKey, Index,
    UniqueConstraint, CheckConstraint, text, TIMESTAMP
)
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP as PG_TIMESTAMPTZ
from sqlalchemy.orm import Mapped, mapped_column, relationship
from src.db.session import Base


class PositionStatus(str, Enum):
    """Status of a trading position."""
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    STOPPED = "STOPPED"
    LIQUIDATED = "LIQUIDATED"


class AccountSide(str, Enum):
    """Trading account side (hedge mode)."""
    LONG = "LONG"
    SHORT = "SHORT"


class Signal(Base):
    """
    Trading signal generated by the orchestrator or external source.
    Contains entry parameters, stop-loss, take-profit, and signal_metadata.
    """
    __tablename__ = "signals"
    __table_args__ = (
        Index("ix_signals_account_id_status", "account_id", "status"),
        Index("ix_signals_created_at_desc", "created_at", postgresql_using="btree", postgresql_ops={"created_at": "DESC"}),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    account_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[AccountSide] = mapped_column(String(10), nullable=False)
    
    entry_price: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    stop_loss: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 8), nullable=True)
    take_profit: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 8), nullable=True)
    quantity: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    leverage: Mapped[int] = mapped_column(Integer, default=1)
    
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    signal_metadata: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)
    
    created_at: Mapped[datetime] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True), 
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    positions: Mapped[list["Position"]] = relationship(back_populates="signal", lazy="selectin")

    def __repr__(self) -> str:
        return f"<Signal(id={self.id}, account_id={self.account_id}, symbol={self.symbol}, side={self.side})>"


class Position(Base):
    """
    Active or historical trading position.
    Tracks PnL, fees, and trailing stop adjustments.
    """
    __tablename__ = "positions"
    __table_args__ = (
        Index("ix_positions_account_id_status", "account_id", "status"),
        Index("ix_positions_signal_id", "signal_id"),
        Index("ix_positions_created_at_desc", "created_at", postgresql_using="btree", postgresql_ops={"created_at": "DESC"}),
        CheckConstraint("quantity > 0", name="chk_quantity_positive"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    signal_id: Mapped[int] = mapped_column(ForeignKey("signals.id", ondelete="CASCADE"), nullable=False, index=True)
    account_id: Mapped[str] = mapped_column(String(50), nullable=False)
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    side: Mapped[AccountSide] = mapped_column(String(10), nullable=False)
    
    entry_price: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    current_price: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    stop_loss: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 8), nullable=True)
    take_profit: Mapped[Optional[Decimal]] = mapped_column(Numeric(19, 8), nullable=True)
    quantity: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    leverage: Mapped[int] = mapped_column(Integer, default=1)
    
    status: Mapped[PositionStatus] = mapped_column(String(20), default=PositionStatus.OPEN)
    realized_pnl: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    unrealized_pnl: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    total_fees: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    
    trailing_log: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=list)
    exchange_order_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    
    opened_at: Mapped[Optional[datetime]] = mapped_column(PG_TIMESTAMPTZ(timezone=True))
    closed_at: Mapped[Optional[datetime]] = mapped_column(PG_TIMESTAMPTZ(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    signal: Mapped["Signal"] = relationship(back_populates="positions")

    def __repr__(self) -> str:
        return f"<Position(id={self.id}, symbol={self.symbol}, side={self.side}, status={self.status})>"


class AccountSnapshot(Base):
    """
    Periodic snapshot of account balance and margin.
    Used for equity curve calculation and risk monitoring.
    """
    __tablename__ = "account_snapshots"
    __table_args__ = (
        Index("ix_snapshots_account_id_created_at", "account_id", "created_at"),
        UniqueConstraint("account_id", "timestamp", name="uq_account_timestamp"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    account_id: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    
    balance: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    equity: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    free_margin: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    used_margin: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    unrealized_pnl: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    
    timestamp: Mapped[datetime] = mapped_column(PG_TIMESTAMPTZ(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )

    def __repr__(self) -> str:
        return f"<AccountSnapshot(id={self.id}, account_id={self.account_id}, equity={self.equity})>"


class DailyMetric(Base):
    """
    Aggregated daily performance metrics per account.
    Includes win rate, profit factor, max drawdown.
    """
    __tablename__ = "daily_metrics"
    __table_args__ = (
        Index("ix_daily_metrics_account_id_date", "account_id", "date"),
        UniqueConstraint("account_id", "date", name="uq_account_date"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    account_id: Mapped[str] = mapped_column(String(50), nullable=False)
    
    date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    total_trades: Mapped[int] = mapped_column(Integer, default=0)
    winning_trades: Mapped[int] = mapped_column(Integer, default=0)
    losing_trades: Mapped[int] = mapped_column(Integer, default=0)
    
    gross_profit: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    gross_loss: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    net_pnl: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    total_fees: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    
    max_drawdown: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    peak_equity: Mapped[Decimal] = mapped_column(Numeric(19, 8), default=Decimal("0"))
    end_equity: Mapped[Decimal] = mapped_column(Numeric(19, 8), nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    def __repr__(self) -> str:
        return f"<DailyMetric(id={self.id}, account_id={self.account_id}, date={self.date})>"


class SystemLog(Base):
    """
    Audit log for system events, errors, and state changes.
    Supports structured logging with JSON payload.
    """
    __tablename__ = "system_logs"
    __table_args__ = (
        Index("ix_logs_level_created_at", "level", "created_at"),
        Index("ix_logs_service_created_at", "service", "created_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    service: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    level: Mapped[str] = mapped_column(String(20), nullable=False)  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    
    message: Mapped[str] = mapped_column(Text, nullable=False)
    correlation_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True)
    payload: Mapped[Dict[str, Any]] = mapped_column(JSONB, default=dict)
    
    created_at: Mapped[datetime] = mapped_column(
        PG_TIMESTAMPTZ(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True
    )

    def __repr__(self) -> str:
        return f"<SystemLog(id={self.id}, service={self.service}, level={self.level})>"
